name: dating
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0
  image_picker: ^0.7.4
  firebase_storage: ^8.0.5
  progress_dialog: ^1.2.4
  provider: ^5.0.0
  url_launcher: ^6.0.2
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  uuid: ^3.0.4
  video_thumbnail: ^0.3.3
  path_provider: ^2.0.1
  photo_view: ^0.11.1
  video_player: ^2.1.1
  flutter_facebook_login: ^3.0.0
  http: ^0.13.3
  location: ^4.1.1
  latlong2: ^0.8.0
  smooth_page_indicator: ^0.2.3
  flutter_webrtc: ^0.6.3
  firebase_messaging: ^9.1.3
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.1.0
  in_app_purchase: ^0.5.2
  flutter_ringtone_player: ^3.0.0
  wakelock: ^0.5.1
  flutter_video_compress: 0.3.7+8
  flutter_native_image: ^0.0.6
  flutter_sound: ^8.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  device_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'


flutter:
  uses-material-design: true
  assets:
    - assets/images/